### ISSUE TITLE
Failed to open 'v8.pc': No such file or directory

### ISSUE THREAD

**Issue by samccone** [ry/deno#109]
```
go get -u github.com/ry/deno/...
# pkg-config --cflags v8.pc
Failed to open 'v8.pc': No such file or directory
No package 'v8.pc' found
pkg-config: exit status 1
```

This looked similar to https://github.com/ry/v8worker/issues/23 however the fix recommended there did not fix the problem at hand.

**Comment by mohamedmansour** [comment]
@samccone  did you try this:
```
go get github.com/ry/v8worker2
cd `go env GOPATH`/src/github.com/ry/v8worker2
./build.py # Will take ~30 minutes to compile.
go test
```

**Comment by samccone** [comment]
Yes, everything ended up working just fine, I opened a README change (see linked PR) to clarify that you expect to see this error on initial install.

Thank you.

**Comment by yuqingc** [comment]
ref: https://github.com/ry/deno/issues/60#issuecomment-393762644

**Comment by qti3e** [comment]
duplicate of https://github.com/ry/deno/issues/60#issuecomment-393749532

**Comment by nikitavoloboev** [comment]
I get this error when building it (https://github.com/ry/v8worker2/issues/7). 

Anything I can do to fix it?

**Comment by pkuphy** [comment]
@nikitavoloboev I build successfully using this:

```
$ brew install ccache
$ mkdir -p $GOPATH/src/github.com/ry
$ git clone --recursive -j8 git@github.com:ry/v8worker2.git
$ cd $GOPATH/src/github.com/ryv8worker2
$ pyenv use 2.7.13
$ ./build.py --use_ccache
```

I think the key is to download submodules and to use python2.

Hope this will help.
