### ISSUE TITLE
deno is as curious as the node alphabet. It will not be the next generation of node？

### ISSUE THREAD

**Issue by LengYXin** [ry/deno#114]
Ry how do you do.
Look at the introduction
No package.json, no npm. Not explicitly compatible with Node.
Do not provide network services.
Creating this project is just a simple one runtime ?
deno is as curious as the node alphabet. It will not be the next generation of node.(*^_^*)
English is not good, excuse me.

**Comment by ry** [comment]
Thanks for the interest, but please keep the issues forum technical to reduce the noise. 
(Feel free to email me ry@tinyclouds.org)
