### ISSUE TITLE
testing/util_test.ts import incorrect module

### ISSUE THREAD

**Issue by kitsonk** [ry/deno#119]
On the following line:

https://github.com/ry/deno/blob/7b5fbc71970056515c41f6983fc8e1f8ee443d11/testing/util_test.ts#L16

I believe it is importing a module that does not exist.  I believe the function desired is in `testing/testing.ts`, not `testing/index.ts`.

(I will try to raise a PR for this, just created the issue for tracking)

**Comment by justjavab** [comment]
You should see the speech "Design Mistakes in Node" in the JS Conf. Berlin which is made by RY.

**Comment by ry** [comment]
Fixed 6e884207eecfde5fad4c48169684590b235aa096
