### ISSUE TITLE
what deno can do in a really project?

### ISSUE THREAD

**Issue by qiaoqiao10001** [ry/deno#121]
cant understand why deno published

**Comment by helloli** [comment]
You should see the speech <Design Mistakes in Node> in the JS Conf. Berlin which is made by RY.

**Comment by justjavab** [comment]
You should see the speech "Design Mistakes in Node" in the JS Conf. Berlin which is made by RY.

**Comment by jorgebucaran** [comment]
@qiaoqiao10001 Slides in English too: http://tinyclouds.org/jsconf2018.pdf

**Comment by qti3e** [comment]
Close as off-topic : )
