### ISSUE TITLE
Failed to get -u github.com/ry/deno/...

### ISSUE THREAD

**Issue by JieJiSS** [ry/deno#128]
I've been strictly follow the compile instruction, and `./build.py --use_ccache` has succeeded.
but when I tried to move on, I stuck here:

```bash
$ go get -u github.com/ry/deno/...
# github.com/ry/deno
../deno/dispatch.go:10:26: undefined: BaseMsg
../deno/dispatch.go:30:10: undefined: BaseMsg
../deno/dispatch.go:62:14: undefined: BaseMsg
../deno/dispatch.go:68:34: undefined: Msg
../deno/dispatch.go:117:13: select case must be receive, send or assign recv
../deno/fetch.go:13:11: undefined: Msg
../deno/fetch.go:16:8: undefined: Msg_FETCH_REQ
../deno/fetch.go:29:14: undefined: Msg
../deno/main.go:38:15: undefined: Asset
../deno/main.go:110:19: undefined: Msg
../deno/main.go:110:19: too many errors
```

OS: macOS 10.12
`go version`: go version go1.10.2 darwin/amd64
current directory: ~/go/src/github.com/ry/deno

ls:
```bash
$ ls
LICENSE			deno_dir.go		globals.ts		os_test.go		timers.go		util.ts
Makefile		deno_dir_test.go	integration_test.go	package.json		timers.ts		util_test.go
README.md		dispatch.go		main.go			runtime.ts		tsconfig.json		v8_source_maps.ts
TODO.txt		dispatch.ts		main.ts			testdata		tslint.json		v8worker2.d.ts
cmd			echo.go			msg.proto		testing			types.ts		yarn.lock
deno.d.ts		fetch.go		os.go			tests.ts		url.js
deno.ts			fetch.ts		os.ts			text-encoding.d.ts	util.go
```

**Comment by qti3e** [comment]
@JieJiSS Use `make`
```bash
cd $GOPATH/src/github.com/ry/deno
make
```

**Comment by JieJiSS** [comment]
```bash
$ make
protoc --go_out=. msg.proto
protoc-gen-go: program not found or is not executable
--go_out: protoc-gen-go: Plugin failed with status code 1.
make: *** [msg.pb.go] Error 1
```

**Comment by qti3e** [comment]
Install `protoc-gen-go`:
```
go get -u github.com/golang/protobuf/protoc-gen-go
go get -u github.com/jteeuwen/go-bindata/...
```

**Comment by JieJiSS** [comment]
Well I managed to solve it by running

```bash
export PATH=$PATH:$GOPATH/bin/
```

**Comment by JieJiSS** [comment]
@qti3e yeah I did install it before but it occurs that the $PATH was incorrect

I'm not quite sure whether it should be set automatically by `go get` or not...

**Comment by qti3e** [comment]
@JieJiSS you should add `$GOPATH/bin` to your `$PATH`

**Comment by kitsonk** [comment]
It is mentioned in the instructions that the `$GOPATH/bin` needs to be in your path for this specific reason. As far as I am aware on macOS no process does but giving specific instructions to set your `$PATH` for something that is an early prototype is likely not warranted. Mentioning should be sufficient, IMO.

**Comment by JieJiSS** [comment]
@kitsonk Well, I focused on bash codes in README.md and didn't recognized that... apologize

thanks for your help!
