### ISSUE TITLE
module management for project...?

### ISSUE THREAD

**Issue by zslucky** [ry/deno#133]
First, Thanks for this project which I always discussed with my mates when we can use TS as runtime in node....

But I'm not sure, if we doesn't have an explicit declaration requirement file for a large project which multi people working on it. Afrer a long time, will the project's dependencies  become uncontrolled? Or what I missed in doc?

**Comment by monkingxue** [comment]
Similar to golang, the dependencies will controlled by url in deno. You can set semantic version in url like `http://deno.com/pkg0.05/index.ts`. Strongly recommend read the [http://tinyclouds.org/jsconf2018.pdf](Design Mistakes in Node)

**Comment by zslucky** [comment]
@monkingxue thank you for reply, I have read the pdf before, no doubt to use semantic version in url, but like golang, it still need `dep` to control the whole project's dependencies right?

**Comment by monkingxue** [comment]
@zslucky Yep, u are right. I use go with govendor, so I guess the deno may add something like this( just guess). However, the premise is that the current project is still in the prototype stage, so various facilities are still under discussion.

**Comment by zslucky** [comment]
@monkingxue thanks. waiting for more tools 😄

**Comment by monkingxue** [comment]
@zslucky please close this issue, thx~

**Comment by zslucky** [comment]
@monkingxue  yes, thanks, look forward to new things
