### ISSUE TITLE
install v8worker2

### ISSUE THREAD

**Issue by 0123cf** [ry/deno#145]
`go get -u github.com/ry/v8worker2`
```
# cd /home/xiexiuyue/deno/src/github.com/ry/v8worker2; git submodule update --init --recursive
Submodule 'depot_tools' (https://chromium.googlesource.com/chromium/tools/depot_tools.git) registered for path 'depot_tools'
Submodule 'v8' (https://github.com/v8/v8.git) registered for path 'v8'
Cloning into 'depot_tools'...
fatal: unable to access 'https://chromium.googlesource.com/chromium/tools/depot_tools.git/': Failed to connect to chromium.googlesource.com port 443: Connection refused
fatal: clone of 'https://chromium.googlesource.com/chromium/tools/depot_tools.git' into submodule path 'depot_tools' failed
package github.com/ry/v8worker2: exit status 128
```
then 
`git submodule update --init`
```
Cloning into 'depot_tools'...
fatal: unable to access 'https://chromium.googlesource.com/chromium/tools/depot_tools.git/': Failed to connect to chromium.googlesource.com port 443: Connection refused
fatal: clone of 'https://chromium.googlesource.com/chromium/tools/depot_tools.git' into submodule path 'depot_tools' failed
```
then rm v8 & clone v8 
```v8 fatal: mmap failed: Cannot allocate memory```

**Comment by 0123cf** [comment]
`git config --global http.proxy`
null
env | grep -i proxy
null

**Comment by pandaCure** [comment]
I also encountered this problem, seeking a detailed solution

**Comment by ztplz** [comment]
Get it by vpn please.

**Comment by 0123cf** [comment]
alreay  use sadowsocks @ztplz

**Comment by Athedorer** [comment]
I have the same problem with @0123cf , on windows, using lantern

**Comment by 0123cf** [comment]
shadowsocks this is sock5 proxy, so we need to set up a proxy, run it
```
git config --global http.proxy 'socks5://127.0.0.1:1080' 
git config --global https.proxy 'socks5://127.0.0.1:1080'
```
solve the problem

**Comment by 0123cf** [comment]
but  clone v8  still
```
fatal: mmap failed: Cannot allocate memory   
```
depot_tools dir no‘t  problem

**Comment by superlbr** [comment]
strong recommend docker https://github.com/maxmcd/deno-docker (slim version about 100MB)

**Comment by terasum** [comment]
you can try set system-level proxy by:
```
export http_proxy="http://127.0.0.1:1081"
export https_proxy="http://127.0.0.1:1081"
```
and then run build.py

**Comment by 0123cf** [comment]
Summary, because of the agent problem, turn socks to http.

i run it

sudo apt-get install privoxy
sudo vim /etc/privoxy/config
```
#        forward-socks4   /               socks-gw.example.com:1080  .
forward-socks5   /               127.0.0.1:1080 .
```
service privoxy start
env | grep -i proxy
unset ALL_PROXY
export http_proxy=http://127.0.0.1:8118/
export http_proxy=https://127.0.0.1:8118/

![](https://user-images.githubusercontent.com/22963895/41025200-dd9a3a9c-69a3-11e8-955b-e2a30c4c2751.png)

**Comment by arlor** [comment]
`go get -u github.com/ry/v8worker2` is done, but when I execute `./build.py --use_ccache`, I got this error:

> out_path None
Rebuilding V8
Fetching dependencies.
Traceback (most recent call last):
  File "build.py", line 149, in <module>
    main()
  File "build.py", line 85, in main
    lib_fn = Rebuild()
  File "build.py", line 97, in Rebuild
    EnsureDeps(v8_path)
  File "build.py", line 146, in EnsureDeps
    env=env)
  File "D:\Python\Python36\lib\subprocess.py", line 286, in check_call
    retcode = call(*popenargs, **kwargs)
  File "D:\Python\Python36\lib\subprocess.py", line 267, in call
    with Popen(*popenargs, **kwargs) as p:
  File "D:\Python\Python36\lib\subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "D:\Python\Python36\lib\subprocess.py", line 997, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] 系统找不到指定的文件。

**Comment by 0123cf** [comment]
https://github.com/ry/deno/issues/60 @arlor
