### ISSUE TITLE
怎么感觉Deno和Node关系不是很大呢？

### ISSUE THREAD

**Issue by kuaidjun** [ry/deno#156]
node 是提供一个在服务端的js运行时（准确说不应该是js，因为缺少了dom和bom）
deno是提供一个在服务端的ts运行时 （目前好像并没有成熟的ts解释器，而且ts是js的超集，所以为什么用ts而不遵循es标准呢  ）
如果deno发布  那是不是意味着 两种语言呈现竞争状态呢？

**Comment by kevinkassimo** [comment]
See #11
