### ISSUE TITLE
go dependencies manager

### ISSUE THREAD

**Issue by terasum** [ry/deno#158]
when making deno, it crash with:
```
go build -o deno ./cmd
os.go:7:2: cannot find package "github.com/spf13/afero" in any of:
	/usr/local/go/src/github.com/spf13/afero (from $GOROOT)
	/home/chenquan/Workspace/go/src/github.com/spf13/afero (from $GOPATH)
Makefile:40: recipe for target 'deno' failed

```

how about adding a package manager like [dep](https://github.com/golang/dep) ?

**Comment by monkingxue** [comment]
In your case, you just need to go get the afero.

**Comment by terasum** [comment]
Yes! I fixed this by `go get`, but does this project needs packages manager? I think this is a high priority question.

**Comment by qti3e** [comment]
Close as off-topic : )
