### ISSUE TITLE
Failed: fail to run "make"

### ISSUE THREAD

**Issue by ThatToti** [ry/deno#159]
```
$ cd $GOPATH/src/github.com/ry/deno

$ make
protoc --go_out=. msg.proto
make: protoc: No such file or directory
make: *** [msg.pb.go] Error 1
```

I encounter this problem,and stuck here. 

Maybe there are some similar problems #128 #71 

But it can not solve my problem

Anyone can help?Thanks

> OS: macOS 10.13.2
> go version: go version go1.10.2 darwin/amd64
> current directory: ~/go/src/github.com/ry/deno

**Comment by ztplz** [comment]
run `export PATH=$PATH:$HOME/go/bin:$GOPATH/bin` and get `protoc-gen-go` again

**Comment by ThatToti** [comment]
@terasum @ztplz  I did install the `protoc-gen-go`,but it still throws the error
```
protoc --go_out=. msg.proto
make: protoc: No such file or directory
make: *** [msg.pb.go] Error 1
```

**Comment by ThatToti** [comment]
Okay,I found the problem.

In the Compile Instructions,we run
```
brew install protobuf
```

It should install `protoc` at the same time,but for some reasons,it will fail.

When we run `make` ,it will throws the error
```
protoc --go_out=. msg.proto
make: protoc: No such file or directory
make: *** [msg.pb.go] Error 1
```

To install `protoc`,we can alternately install as followed instructions:
> Mac OS
```
PROTOC_ZIP=protoc-3.3.0-osx-x86_64.zip
curl -OL https://github.com/google/protobuf/releases/download/v3.3.0/$PROTOC_ZIP
sudo unzip -o $PROTOC_ZIP -d /usr/local bin/protoc
rm -f $PROTOC_ZIP
```

> Linux
```
PROTOC_ZIP=protoc-3.3.0-linux-x86_64.zip
curl -OL https://github.com/google/protobuf/releases/download/v3.3.0/$PROTOC_ZIP
sudo unzip -o $PROTOC_ZIP -d /usr/local bin/protoc
rm -f $PROTOC_ZIP
```

That's it.

@ztplz @terasum Thanks for your suggestions.
