### ISSUE TITLE
Is stacking gc languages really the best idea?

### ISSUE THREAD

**Issue by ForsakenHarmony** [ry/deno#165]
I feel like go is not the best choice

**Comment by TomasHubelbauer** [comment]
Ryan seems to be considering Rust and C++, too, which would address this. (I'm particularly fond of the thought of rewriting this in Rust.)

**Comment by monkingxue** [comment]
The existing solutions are mainly considered from the perspective of easy implementation. It is less difficult to achieve with go.

**Comment by lukeed** [comment]
Nothing new here, but Rust seems like the obvious choice -- especially given that Deno has/will have a renewed focus on systems APIs. Personally, Rust _feels_ closer to JavaScript, too~!

Either way, curious to see how deno & all its experiments along the way take shape 👍

**Comment by jacktuck** [comment]
@lukeed I think you're absolutely right Rust feels closer when you look at generics and such. Don't think Ryan is sold on Go yet and the codebase is lean enough to change languages most likely. https://github.com/ry/deno/search?l=go&p=1

**Comment by lukeed** [comment]
Aye, definitely. The possibility of switching (and to Rust, specifically) has been mentioned a few times already across other issues, as well as in the introductory talk too.

I'm just echoing my preference 😄I recently resolved my own 6-mo internal debate of Go-v-Rust for some of my own projects, some of which share deno's need for secure boxes & systems integrations. Just thought I'd help push in the _right_ (😉kidding) direction.

**Comment by rurban** [comment]
Yes, it's the best idea. 
First GC languages are safe, refcounted typically not. Esp. rust is unsafe with memory and concurrency, C++ ditto. This projects goal is safety first.

A good point for rust would be abstractions with macros and generics. But there are safe and fast languages for these. ATS or Pony would come to my mind.

**Comment by TomasHubelbauer** [comment]
As per #94, this is not a time and place to discuss this, but would you please consider emailing me (email is in my profile) elaborating on how Rust is unsafe with memory and concurrency? The language was design with the stated goal of the exact opposite, safety, so I am curious to see why you think it's failing at that.

**Comment by qti3e** [comment]
This subject has been discussed many times on many issues; please do **not** open design issues for now.
Close as off-topic : )

**Comment by ry** [comment]
https://github.com/ry/deno/issues/208#issuecomment-395739171
