### ISSUE TITLE
Duplicate resolve the file module firstly

### ISSUE THREAD

**Issue by monkingxue** [ry/deno#175]
Firstly, I clear the `~/.deno/cache` folder, and then run `deno --debug  testdata/002_hello.ts > deno.out`. I found the `resolveModule sourceCode length  28` appeared five times, and the **28** is the length of content in `002_hello.ts`.
What I confused is that why deno need fetch the file module 5 times firstly rather than cache the content in memory?

**Comment by kitsonk** [comment]
A lot of it is related to they way TypeScript compiles and runs programmes.  You would have to go through in more detail analysis of dumping the stack at each point, but it is rather complex.  There are some efficiencies that can be had, possibly things that can be pushed upstream into TypeScript, but I suspect that isn't a major priority in the backlog at the moment.

**Comment by monkingxue** [comment]
Thanks for ur answer and I cannot agree  more
