### ISSUE TITLE
Hope to be able to synchronize Chinese documents for the first time

### ISSUE THREAD

**Issue by roonly** [ry/deno#178]

**Comment by kevinkassimo** [comment]
I don't think Ryan is having any plans for this at current early stage of being simply a "demo". And check out #94

Transcript:
我不认为Ryan现阶段有任何这样的计划，毕竟还只是在开发demo的初期。他的态度详见 #94

**Comment by ThatToti** [comment]
Deno is in the very beginning.

It's not a proper time to release a Chinese version.Maybe some time later.

**Comment by monkingxue** [comment]
@qti3e Close this issue please, thx~

**Comment by qti3e** [comment]
Closed as off-topic : )
