### ISSUE TITLE
Add youtube link to your Deno talk to `Readme.md`

### ISSUE THREAD

**Issue by somombo** [ry/deno#180]
I was wondering if you could kindly add this link https://www.youtube.com/watch?v=M3BM9TB-8yA
to your talk (or if perhaps you have a better link) to the main readme or perhaps in the repo description where the people often put the repo website link.

This will help people who prefer video get a better understanding behind the motive for this project.

Great talk, great ideas! 
> ps:- I prefer `rustlang` to `golang` personally 😉 

Thank you!

**Comment by somombo** [comment]
added in PR https://github.com/ry/deno/pull/181

**Comment by ThatToti** [comment]
That is a good idea

**Comment by DamianRivas** [comment]
+1 on `rustlang`
