### ISSUE TITLE
Support JavaScript?

### ISSUE THREAD

**Issue by luneice** [ry/deno#184]
Deno is a secure TypeScript runtime on V8, can javascript run it ?

**Comment by f-a-a** [comment]
In Ryan's talk, he mentioned that since TypeScript is a superset of JavaScript. It should also work out of the box.

ref: https://youtu.be/M3BM9TB-8yA?t=22m32s

**Comment by brunofin** [comment]
TypeScript is a JS supertype. Every JS is TS code.

@ry mentioned that in a recent talk at JSConf EU this year.
You can watch it here, it's worth your time:) 

https://youtu.be/M3BM9TB-8yA?t=15m53s

**Comment by luneice** [comment]
And i can use javascript as before?
like es5 or latest features？

**Comment by yoyo837** [comment]
@luneice For you, See http://www.typescriptlang.org/

**Comment by cozzbie** [comment]
More like 'Every TS is JS code.' @brunofin

**Comment by luneice** [comment]
Thanks for your help.

**Comment by brunofin** [comment]
@cozzbie nop. The following is TS:

```typescript
class SomethingDao extends BaseDao {
    public static findSomething(id: string): Something {
        const something: Something = doSomething();
        return something;
    }
}
``` 

copy/paste it into your browser's JS console and see what happens.

**Comment by gillchristian** [comment]
This is not the place to discuss if TS is _really_ superset of TS or not. Let's not add noice with such discussions.
