### ISSUE TITLE
What is deno’s goal?

### ISSUE THREAD

**Issue by chijitui** [ry/deno#186]
It is different from node focus, deno is more biased towards the browser, can i understand this?

and I hope to be able to export Chinese documents first.

**Comment by apkd** [comment]
You might be interested in these slides: http://tinyclouds.org/jsconf2018.pdf
Live talk here: https://www.youtube.com/watch?v=M3BM9TB-8yA

**Comment by chijitui** [comment]
@apkd well, thanks!
