### ISSUE TITLE
Logo Suggestions

### ISSUE THREAD

**Issue by nothingismagick** [ry/deno#192]
![screen shot 2018-06-07 at 16 33 40](https://user-images.githubusercontent.com/35242872/41106624-afbc55f6-6a70-11e8-8a4e-186ad323910d.png)

![screen shot 2018-06-07 at 16 58 36](https://user-images.githubusercontent.com/35242872/41108937-1ab3139a-6a76-11e8-874b-c4094fe8ea2f.png)
![screen shot 2018-06-07 at 17 03 52](https://user-images.githubusercontent.com/35242872/41108938-1ad5609e-6a76-11e8-8e9d-338aa7406791.png)

**Comment by shekohex** [comment]
What! Is that the same font used in Nodejs logo?

**Comment by jacktuck** [comment]
It doesn't need a logo right now. It's an unstable prototype, more of an idea at this point (a good one i think, though.

**Comment by userpixel** [comment]
Probably it doesn't need a logo at this time but can't stop people's creativity. 🎉
I [wrote a little about what to consider when making a logo](https://medium.com/@alexewerlof/a-logo-for-deno-13d4a90867f) for something like this project given its history and goals. Don't take everything seriously. Let's have some fun! 😊Some people will contribute to the code, some to the documentation and some help other things. There'll be place for everybody.

**Comment by nothingismagick** [comment]
I had just watched the JS conf talk and thought it would be a funny idea to riff on the NodeJS logo like the repo name. Awesome that everybody hates it!!! That was my intention. Maybe now that you've all gotten it out of your system, we could have a discussion about it...

**Comment by kitsonk** [comment]
A discussion about what? A logo? Seriously?

**Comment by nothingismagick** [comment]
Yeah, why not?

**Comment by nothingismagick** [comment]
15000 :star:'s, over a hundred commits. I know it isn't ready for production, but why the hate?

**Comment by kitsonk** [comment]
> Awesome that everybody hates it!!! That was my intention.

So you intention was to troll everyone into having a serious conversation about a logo for an early prototype project. 🙄

**Comment by nothingismagick** [comment]
@kitsonk - wish there was really a way to use sarcasm appropriately, that's hard in this format. I was not trying to troll anyone, and used the logo sketch as a tongue-in-cheek way to riff on the node.js logo. 

I am really sorry to have bothered you with something that you obviously consider non-essential in an "early prototype project", as you say. I personally believe it is never to late to think about things like design in software projects, both from an engineering perspective as well as from a visual perspective. 

I mean, that is ultimately the idea here, no? To rethink the ways of working with V8 that are smarter and using lessons learned to make things better.

**Comment by ry** [comment]
I appreciate the interest - but there are many infrastructural issues to be worked out first. 
Please help me by keeping non-technical discussions out of the issues.
