### ISSUE TITLE
Does the goal of the repo support multi thread?

### ISSUE THREAD

**Issue by xialvjun** [ry/deno#197]
if support multi thread? how to process the event loop? And what does the atom type look like?

**Comment by kevinkassimo** [comment]
libuv replaced by Goroutine + channel + WaitGroup, maintaining mostly the same functionality. See `DispatchLoop()` in `dispatch.go`. v8 is kept as sandbox (unlike node), and IO tasks are passed to Go through messaging.
(please correct me if I have any misinterpretation, thx!)

**Comment by xialvjun** [comment]
But @ry said there is some possibility to write deno with rust. 
https://github.com/ry/deno/issues/11#issuecomment-394171740
So, maybe we should not limit ourselves in goroutine

**Comment by kevinkassimo** [comment]
Yeah that's a choice, but even in Rust should not change the essence of the core ideas

**Comment by ry** [comment]
I would like to add workers at some point - if that's what you mean. JavaScript is single threaded tho.
