### ISSUE TITLE
Idea about assets during development

### ISSUE THREAD

**Issue by matiasinsaurralde** [ry/deno#202]
I've been hacking on this branch in order to disable `go-bindata` during development, you may find it useful:
https://github.com/matiasinsaurralde/deno/commits/asset-loader

So I use `make dev` instead of `make` and the build process only involves TS tasks and a Go build.

What do you think?

**Comment by phated** [comment]
I've been using `packr` in https://github.com/phated/reasonable and I like it alot - It has good dev and prod support.

**Comment by matiasinsaurralde** [comment]
@phated Very cool!

**Comment by ry** [comment]
Including assets is integrally tied into V8 snapshots - I've done some work along these lines. In the deno2 branch you can see how they will get included: https://github.com/ry/deno/blob/110ddab670cbf477488cceeea2842c980942d7b8/deno2/main.cc#L10
