### ISSUE TITLE
Plans for rewrite in Rust

### ISSUE THREAD

**Issue by doutchnugget** [ry/deno#208]
Any plans to rewrite in Rust?

**Comment by kevinkassimo** [comment]
Ryan is considering the option. For now this Go version is served as more of a demo for examining the idea

**Comment by TomasHubelbauer** [comment]
See also #165

**Comment by ry** [comment]
Yes I think so. I have a private branch that is exploring snapshotting + better build system only in c++, I think that might become the core system where the message passing between V8 and the outside world can be unit tested. Once that's working I will experiment with binding to Rust.

The reason for not using Go is that it has a rather complex runtime - including a GC. Although I haven't experienced any problems with that yet, it's not hard to imagine that down the road that might clash badly with V8's very complex runtime.
