### ISSUE TITLE
I'm just start learning node, you changed 4 letter order and let me learn a new one?

### ISSUE THREAD

**Issue by leniy** [ry/deno#211]
I am old, node_modules are bothering me, LET ME GO, pls.

Star this repo, and I will not Watch until 1/4 of `node` plugins support `deno`

**Comment by qti3e** [comment]
please don't open issues like this; issue tracker is to track the technical problems.

**Comment by timurmaio** [comment]
@leniy nobody wants you to learn something new. It is only your choice, as a Ryan's to make something new. Please, stop open issues such this.
