### ISSUE TITLE
Maybe go to Gitlab?

### ISSUE THREAD

**Issue by kuroljov** [ry/deno#212]
Hey,

Want to say that my idea **has nothing to do** with the fact that Github is being bought by Microsoft.

It's more like a [Gitlab PRO is free for Open Source Now](https://about.gitlab.com/2018/06/05/gitlab-ultimate-and-gold-free-for-education-and-open-source/) type of thing. Obviously Gitlab can offer much more out of the box :smile_cat: 

Any thoughts? @ry

**Comment by ry** [comment]
no thanks.
