### ISSUE TITLE
edon

### ISSUE THREAD

**Issue by tyrsius** [ry/deno#216]
just wanted to throw this out there. A coworker came up with it. Deno is kind of an awkward name, but its clearly trying to be an anagram of node.

edon is also an anagram of node, but is also a nice homophone of eden (the magical paradise that node could have been).

**Comment by gillchristian** [comment]
Please don't open this kind of issues ([#192 (comment)](https://github.com/ry/deno/issues/192#issuecomment-395822805)).

Ryan picked the name for a reason, whatever it might be, and he did not make that an open discussion. Let's respect the author's decisions.

**Comment by ry** [comment]
Thanks for the interest but please help me by not posting non-technical issues.

**Comment by tyrsius** [comment]
Sorry, will do.
