### ISSUE TITLE
tag deno as the next generation of node or not

### ISSUE THREAD

**Issue by calidion** [ry/deno#218]
As someone is endlessly arguing that deno is or not the next generation of node, 

which is quite confusing and misleading.

I would like to hear from an official announcement.

Can deno be called the next generation of node or not?

Please make it clear and stop this argument.

Thank you.

**Comment by gillchristian** [comment]
Please don't open this kind of issues. Ryan already stated his goals [here](https://github.com/ry/deno#status). You can check the [slides](http://tinyclouds.org/jsconf2018.pdf) & [JS conf talk](https://youtu.be/M3BM9TB-8yA).

Also here requested to keep this discussions out of issues [#192 (comment)](https://github.com/ry/deno/issues/192#issuecomment-395822805)

**Comment by monkingxue** [comment]
@gillchristian Maybe we should write a template comment for this kind of issues 😆

**Comment by calidion** [comment]
As it is a fundamental and technical problem. 

And currently some think it is while others think otherwise. 

it has been a hot topic now.

To avoid such misleading and useless articles, and help people deep understand deno.

it may be necessary to have a clear addressing on this.

**Comment by ry** [comment]
I discussed this in the talk linked above.
And please help me by keeping the noise levels down in the issues.

**Comment by monkingxue** [comment]
@calidion The main goal at present is not to let people understand deno, but to develop it as soon as possible can be used normally. Facts speak louder than words, isn't it?

**Comment by calidion** [comment]
@monkingxue 

Totally agree.

But there are always someone trying to misleading people with fake facts and always projects (shamelessly) announcing them the next generation one :)

@ry 

sorry for the disturbance.

**Comment by gillchristian** [comment]
@monkingxue seems like a good idea. I'm on the phone now but later can create a PR with a template for issues, let's hope that will help.
