### ISSUE TITLE
Stuck building deno

### ISSUE THREAD

**Issue by davedx** [ry/deno#223]
I followed the instructions, but when I try to run this part:

cd $GOPATH/src/github.com/ry/deno

make

I get this:

dave$ make
protoc --go_out=. msg.proto
protoc-gen-go: program not found or is not executable
--go_out: protoc-gen-go: Plugin failed with status code 1.
make: *** [msg.pb.go] Error 1

I do have protoc-gen-go in my GOPATH:

/Users/dave/go/src/github.com/golang/protobuf/protoc-gen-go

echo $GOPATH
/Users/dave/go/

Is there something obvious I'm missing? I'm not familiar with go :)

**Comment by monkingxue** [comment]
@davedx Can you run the `protoc-gen-go` separately and show the result？

**Comment by davedx** [comment]
dave$ protoc-gen-go
-bash: protoc-gen-go: command not found
Daves-MacBook-Pro:protoc-gen-go dave$ go protoc-gen-go
go: unknown subcommand "protoc-gen-go"

Do I need to add protobuff to the GOPATH or something?

**Comment by monkingxue** [comment]
You need `go build` and `go install` the protoc-gen-go

**Comment by davedx** [comment]
OK, did that. It's still not working. I think something went wrong with the installation of Go and paths weren't set (GOPATH, GOBIN), so I'm having to set these up manually and work out what they should be. I now have:

dave$ echo $GOPATH
/Users/dave/go/
Daves-MacBook-Pro:deno dave$ echo $GOBIN
/Users/dave/go/bin

The compiled binary for protoc-gen-go is now in $GOBIN:

dave$ pwd
/Users/dave/go/bin
Daves-MacBook-Pro:bin dave$ ls -l
total 17136
-rwxr-xr-x  1 dave  staff  2772640 Jun  9 09:19 go-bindata
-rwxr-xr-x  1 dave  staff  6000640 Jun  9 16:30 protoc-gen-go

But the make command for deno still fails:

make
protoc --go_out=. msg.proto
protoc-gen-go: program not found or is not executable
--go_out: protoc-gen-go: Plugin failed with status code 1.
make: *** [msg.pb.go] Error 1

**Comment by davedx** [comment]
Aha, I was missing $GOBIN my $PATH. Of course. I don't know why the go installer doesn't set these up for you. It's not building deno!

**Comment by monkingxue** [comment]
@davedx Congratulations! Please do try deno~

**Comment by monkingxue** [comment]
@davedx And you can close this issue, thx~
