### ISSUE TITLE
Question about the future of Deno and Nodejs

### ISSUE THREAD

**Issue by happilymarrieddad** [ry/deno#245]
Hello,

I was wondering what hole Deno is going to fill? Is it supposed to be a long-term replacement for Nodejs? What are the advantages of Deno vs Go? Is it going to compete with Go or does it solve different problems? Thanks and sorry if these are dumb questions. I'm just really curious about this project!

- Nick

**Comment by kldavis4** [comment]
please see https://github.com/ry/deno#github-noise

**Comment by qti3e** [comment]
Closing this issue.

Please let's try to keep the issues as quiet as possible. It makes it difficult for contributors to give attention to important (technical) matters.

**Comment by brucod** [comment]
@happilymarrieddad -- Watch Ryan's talk and it will fill in a lot of blanks: [10 Things I Regret About Node.js - Ryan Dahl - JSConf EU 2018](https://www.youtube.com/watch?v=M3BM9TB-8yA)
