### ISSUE TITLE
Question on CI/CD pipeline, testing for future projects based on deno

### ISSUE THREAD

**Issue by valaydesai3** [ry/deno#246]
I know deno is still in development phase. Currently the project I am working with has Jenkins based CI/CD pipeline. Pipeline runs on every push to feature branch and execute npm install and other scripts and tests on docker container. 

So, any thoughts on how will it be with deno ? Especially when there's no npm and backward compatibility. Will there be a new testing framework for deno ?

**Comment by qti3e** [comment]
Deno will have internal testing tools, see #20, so there is no need for things like Jest or Chai : )
There is no npm (or any other package manager) for Deno hence no need to run `npm install`
