### ISSUE TITLE
What about the existing node API?

### ISSUE THREAD

**Issue by demian85** [ry/deno#250]
I'm struggling to understand if deno needs a complete new API from scratch or the existing node API can be ported somehow.
Is the idea to have an API 100% written in Typescript? Aren't declaration files enough at least for now?

Thanks.

**Comment by ZanderBrown** [comment]
Declaration files require an existing JavaScript implementation, Node API is largely native methods exposed to a V8 runtime & deno works differently by design

**Comment by ry** [comment]
Deno will not be compatible with Node's API. We will leave to user code to bridge that gap, if necessary.
