### ISSUE TITLE
Un ha ! i don't want to study!!

### ISSUE THREAD

**Issue by mengxiaof** [ry/deno#26]

**Comment by IEasying** [comment]
good good study， day day up ！

**Comment by ren5488001** [comment]
吾生而有涯，而学无涯

**Comment by aqiongbei** [comment]
Don't open another issues! https://github.com/ry/deno/issues/25

**Comment by abnerCrack** [comment]
please close this issues.

**Comment by deot** [comment]
- - ！

**Comment by limengke123** [comment]
Don't open another issues!

**Comment by JDEast1029** [comment]
666

**Comment by RemielOrz** [comment]
what

**Comment by dinglittle** [comment]
世上本是没有路的

**Comment by zengming00** [comment]
来学我的 https://github.com/zengming00/go-server-js

**Comment by swdnzh** [comment]
火钳留名

**Comment by TeanWang** [comment]
I wanna go back to 2010

**Comment by relign** [comment]
请勿在 Issues 页面无意义灌水，此类行为属于对 Issues 区的滥用。

Please stop sending anything that is not related to this project. Doing this is a kind of abusing Issue Tracker.

**Comment by lizebang** [comment]
@mengxiaof 
Please close this issue.
请关掉这个 issue。

**Comment by dwqs** [comment]
@ry @mengxiaof This issue is no sense, close it, please.

**Comment by kanting** [comment]
@ry This issue is no sense, close it, please.
