### ISSUE TITLE
没钱用  肯定要学啊 不学就没有钱用

### ISSUE THREAD

**Issue by wangkai000** [ry/deno#27]
打工是不可能打工的

**Comment by JasinYip** [comment]
有完没完了？

**Comment by Enginebeck** [comment]
别的又不会做，只会学习...

**Comment by kanting** [comment]
@ry  please close this issue

**Comment by RubyLouvre** [comment]
前排摆摊子卖瓜子汽水！

**Comment by 0123cf** [comment]
做生意又不会做， 只能写写前端维持生活这样子。

**Comment by uknowzheng** [comment]
在家里一个人好无聊，都没有朋友玩，没有女仔玩。进了github个个都是人才，说话有好听，超喜欢里面的。

**Comment by laosb** [comment]
请勿在 Issues 页面无意义灌水，此类行为属于对 Issues 区的滥用。

**Comment by hax** [comment]
Here is NOT the chatroom, behavior yourself!

请不要再灌水了，中国开发者的脸都被你们丢光了。

**Comment by lizebang** [comment]
@wangkai000 
Please close this issue.
请关掉这个 issue。

**Comment by kanting** [comment]
@ry  please close this issue
