### ISSUE TITLE
Further Reorg

### ISSUE THREAD

**Issue by ry** [ry/deno#285]
Step 1:
```
//src/tools/ -> //tools/
//.gitignore -> //.gitignore
```

Step 2: (This requires moving many symlinks)
```
//src/BUILD.gn -> //BUILD.gn
//src/.gn -> //.gn
//src/.gclient -> //.gclient
```

Step 3:
```
//src/js/ -> //js/
``` 

Step 4: (may require running `gclient flatten` and `git rm .gclient; git add DEPS` to get V8 to check out into third_party.... this step will require a bit of effort)
```
//v8/ -> //third_party/v8 
```

**Comment by qti3e** [comment]
@ry I think we should have a tslint file in the root? indeed I need that for /website...

**Comment by ry** [comment]
@qti3e sure- tsconfig too
