### ISSUE TITLE
我们老大告诉我：如果你们前端再这么玩，我们就不要前端了。。。。。

### ISSUE THREAD

**Issue by bgl1987** [ry/deno#29]

**Comment by xinchanghao** [comment]
打工是不会打工的

**Comment by Enginebeck** [comment]
@ry plz close this issue.

**Comment by echoturing** [comment]
A secure TypeScript runtime on V8
关你前端什么事..素质极差!

**Comment by laosb** [comment]
请勿在 Issues 页面无意义灌水，此类行为属于对 Issues 区的滥用。

Please stop sending anything that is not related to this project. Doing this is a kind of abusing Issue Tracker.

**Comment by dinglittle** [comment]
A secure TypeScript runtime on V8
关你前端什么事..素质极差!
