### ISSUE TITLE
Could Nexus.js be integrated with deno?

### ISSUE THREAD

**Issue by dou4cc** [ry/deno#291]
[Nexus.js — Multi-threaded I/O for JavaScript.](https://github.com/voodooattack/nexusjs)

The author of Nexus.js [got a serious illness](https://medium.com/@voodooattack/concurrent-javascript-a-years-absence-ea5ae93d3b91) and [does not seem going to recover in a few months](https://github.com/voodooattack/nexusjs/graphs/code-frequency).

This integration requires a switch from V8 to JavaScriptCore and will break the existing event loop-based code. But deno is not born for compatibility and people will be happy to write thread-safe programs for deno because of its compatibility with current event loop-based runtimes and performance advantages.

**Comment by qti3e** [comment]
related to https://github.com/ry/deno/issues/197#issuecomment-395955952

**Comment by ry** [comment]
We're not going to switch to JSCore. I didn't know about Nexus - thanks for the link.

**Comment by shytikov** [comment]
I think MS also created similar (to Nexus) project: https://github.com/Microsoft/napajs

But regardless of implementation details it would be definitely cool if Go could be beaten in performance.
