### ISSUE TITLE
Name proposal

### ISSUE THREAD

**Issue by playerx** [ry/deno#295]
Hi, I respect current name "deno", also I got the idea why deno ;) and like it very much. But I got one idea and want to share, what do you think to call this project: 
`NodeTS`

When I hear TS I've feeling of: Type Safety, Security, Also it has Typescript in core (which is awesome btw), so why not NodeTS?

Just shared this idea :)

**Comment by qti3e** [comment]
Thanks, but this project is entirely different from Node.js, and it has different goals.

( btw, NodeTS is much like `ts-node` :/ )

**Comment by playerx** [comment]
Got it, I think deno will be: nodejs done right, based on current XP. Thanks for answer.

**Comment by playerx** [comment]
Node is a good word and I tried to keep it. I think we all are nodes :)

**Comment by MasterJames** [comment]
For me node was always reserved for visual node connecting editors and was a bad choice as it wasted or collided with the name which was already established in the vernacular for again I say a visual node connectivity system like you see in 3D and compositing applications Houdini nuke etc. First seen in a way with NeXT step but that was just GUI layout.
Obviously de no is no de flipped like least significant byte first.
