### ISSUE TITLE
ninja: error: loading 'build.ninja': No such file or directory

### ISSUE THREAD

**Issue by camilomontoyau** [ry/deno#297]
I've got this error when trying to build 
ninja: error: loading 'build.ninja': No such file or directory
is there a way to create such file?

**Comment by josemariabooymts** [comment]
Wtf Camino?

**Comment by matiasinsaurralde** [comment]
@camilomontoyau Which platform are you using? Can you confirm the current working directory and the command  you're running?

**Comment by ry** [comment]
Make sure you cd into the “out/Debug” dir created by gn

**Comment by camilomontoyau** [comment]
@matiasinsaurralde I'm in OSX high sierra
this is what is happening 
![deno-ninja](https://user-images.githubusercontent.com/5333383/42067930-97f131d6-7b0e-11e8-8337-81d7754f33b4.gif)

**Comment by qti3e** [comment]
@camilomontoyau so this step is the root of your issue `gn gen out/Debug --args='cc_wrapper="ccache" is_debug=true '`
can you tell us what you get when you run that?

**Comment by camilomontoyau** [comment]
@matiasinsaurralde @qti3e 
it was that I haven't installed xcode so the compilers weren't in my mac.

Now that I did compile it, how can I use it? I tried several commands but nothing happened.

**Comment by qti3e** [comment]
@camilomontoyau you should run `./out/Debug/deno` but nothing extraordinary will happen then 
we're in the begging of a massive rewrite in rust, and deno does nothing atm : )

**Comment by camilomontoyau** [comment]
thanks @qti3e for taking the time to answer my questions.
