### ISSUE TITLE
再不要更新了，老子学不动了

### ISSUE THREAD

**Issue by zheng1013757145** [ry/deno#298]
Don't update, I can’t learn

**Comment by kevinkassimo** [comment]
Seriously, issues are for tracking bugs and improvement suggestions. If you are simply seeking to amuse others or for your own amusement, please head somewhere else (reddit or, in China, Tieba)
说真的，issue是用来追踪bug和改进建议的。如果你只是觉得这么评论很好玩的话，建议你还是去reddit或者贴吧（你可能对github的性质存在着什么误会，这段时间看的我真的作为国人十分尴尬
