### ISSUE TITLE
IRC

### ISSUE THREAD

**Issue by robbym** [ry/deno#299]
If there isn't already one, I feel like there should be an IRC, Slack, or other form of chat room.

**Comment by ccravens** [comment]
Or slack maybe? 🤔

**Comment by ccravens** [comment]
+1 for Slack

**Comment by matiasinsaurralde** [comment]
+1 for Slack

**Comment by ry** [comment]
No slack please, it costs money and isn't meant for open source projects. I've set up a gitter: https://gitter.im/denolife/
I can't say I'll hang out there, but I'll try it for a bit.

**Comment by rezonant** [comment]
Yess, gitter is the sauce :-)
