### ISSUE TITLE
What's the view on using Rust nightly?

### ISSUE THREAD

**Issue by robbym** [ry/deno#300]
What's the view on using the up and coming features in nightly?

I ask because one of the features, namely `extern types`, is still brewing in nightly, and its exactly what would be needed to model opaque structs, like `Deno`.

I also ask because I don't if any contributions made to the Rust specific stuff are subject to a specific compiler version or whatever.

Are there any contribution guidelines?

**Comment by ry** [comment]
I’d rather use stable.
As far as contribution guidelines: you should email me before starting any big projects.

**Comment by robbym** [comment]
Understood, thanks.
