### ISSUE TITLE
Add a way to build deno without snapshot (for fast incremental builds when JS changes)

### ISSUE THREAD

**Issue by ry** [ry/deno#311]
Currently [the deno target](https://github.com/ry/deno/blob/6830370c3e4f7d9f09c08fe76f8902193e027c1d/BUILD.gn#L11) depends on the a [V8 snapshot](https://github.com/ry/deno/blob/6830370c3e4f7d9f09c08fe76f8902193e027c1d/BUILD.gn#L173), this is desirable for production builds, but when developing it takes a lot of time to build for each change to the runtime's javascript.

There should be a new target deno_nosnapshot which loads [the runtime bundle](https://github.com/ry/deno/blob/6830370c3e4f7d9f09c08fe76f8902193e027c1d/BUILD.gn#L98-L121) from the filesystem which has much faster incremental builds when there are changes in the `js/` dir.

**Comment by mreinstein** [comment]
issue context/motivation from Ryan:

> I suggest trying to make a change in `js/main.ts` (like add another console.log) and run 

> `ninja -C out/Debug  mock_main`

> to see how slow incremental builds are with the snapshot. It's not such a big deal right now
> because we're not doing much on the runtime, but it's going to get very annoying soon :)
