### ISSUE TITLE
Add script to build deno_third_party git submodule

### ISSUE THREAD

**Issue by ry** [ry/deno#312]
Currently deno requires installing a lot of tooling and dependencies like depot_tools and yarn. This task is preparation for removing these dependencies.

Instead of having gclient check out many git repos, we will have a single flat git submodule called `deno_third_party` which will be checked out at `//third_party/`.

Inside `deno_third_party` will be v8, cpplint, node_modules, and other dependencies listed in .gclient.

However instead of manually maintaining this submodule, we want a script which can read the .gclient file and the package.json file and checkout all the dependencies into the third_party directory. Obviously the person running this script will need to have depot_tools and yarn installed, but people checking out the generated deno_third_party will not need them.
(Note that currently V8 is located at `//v8` and it needs to be moved to `//third_party/v8` first. See #285 step 4)

Only after this script is working will we switch over to the single git submodule.

deno_third_party will also speed up travis by a few minutes.

Ideally this script is written in Python for portability to Windows. Suggested name: `//tools/build_third_party.py`

[This TODO and code](https://github.com/ry/deno/blob/6d288b63cddb3ea8548807895b3ac8e77baa2f51/.travis.yml#L22-L32) should be removed when deno_third_party finally lands.

**Comment by piscisaureus** [comment]
+1, although why write the scrip in python rather than node?

**Comment by ontouchstart** [comment]
@ry Regardless what language to use for automation, I think a docker environment might fit the purpose of developing and testing this submodule `deno_third_party`. 

Furthermore based on this [docker caching technique](https://github.com/ontouchstart/deno/blob/e49b1e7c7b97b76bcc1b19e658ebe7b0b3424562/docker_cache.sh) , it might be possible to use versioned docker images as `caches` for dependency libraries and assets. I can imagine a public versioned deno_third_party docker images for that purpose.

**Comment by ry** [comment]
@ontouchstart I don't want docker to be a build dependency

**Comment by ontouchstart** [comment]
That is fine. Understand your point on Docker. There are many ways to cache dependency assets, submodule, docker, or other packaging system. We all know caching is a hard problem. I have no technical preference on any of these solutions. If participating the development and testing of deno require specifically toolchains and workflows, whatever you decide, people will follow.

Personally I don't like the toolchain dependency on python, especially python2. Some legacy systems have this technology debt on python2 because of toolchain.

**Comment by ry** [comment]
@ontouchstart I don't like the python dependency either - but V8 is deeply dependent on it and thus it's not really up for debate. Other dependencies we have control over should and will be minimized. (Maybe people don't get that impression from the current build instructions, but it is intended to be minimal in the near future.)
