### ISSUE TITLE
PHP果然是最好的语言

### ISSUE THREAD

**Issue by shanjie001** [ry/deno#32]
特来嘲讽，哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈

**Comment by laosb** [comment]
请勿在 Issues 页面无意义灌水，此类行为属于对 Issues 区的滥用。

Please stop sending anything that is not related to this project. Doing this is a kind of abusing Issue Tracker.

**Comment by choleraehyq** [comment]
你们这群弱智又是从哪个社区跟风过来丢人的？

**Comment by kanting** [comment]
貌似是cnode社区的人发了一些大新闻搞事情，所有一股脑的人来issue

**Comment by Yinyiran** [comment]
请勿在 Issues 页面无意义灌水，此类行为属于对 Issues 区的滥用。

Please stop sending anything that is not related to this project. Doing this is a kind of abusing Issue Tracker.
