### ISSUE TITLE
拥抱GO 得永生

### ISSUE THREAD

**Issue by eds** [ry/deno#34]
拥抱GO 得永生

**Comment by V-Tom** [comment]
拥抱GO 得永生

**Comment by nodece** [comment]
拥抱GO 得永生

**Comment by laosb** [comment]
请勿在 Issues 页面无意义灌水，此类行为属于对 Issues 区的滥用。

Please stop sending anything that is not related to this project. Doing this is a kind of abusing Issue Tracker.
