### ISSUE TITLE
求别更新，老子学不动了

### ISSUE THREAD

**Issue by WanZz8** [ry/deno#354]

**Comment by xiewang** [comment]
敢不敢报上你的经纬度

**Comment by WanZz8** [comment]
@xiewang 这些毛子天天更新代码！母语是英语就很牛逼啊

**Comment by hfpp2012** [comment]
没文化和素质在你身上体现得淋漓尽致，回到受小学教育吧

**Comment by hfpp2012** [comment]
盲目跟风，还跟的是过去的风，是傻逼的一大特征

**Comment by STLighter** [comment]
Close it plz

**Comment by HenryYong** [comment]
shame on YOU!

**Comment by whtiehack** [comment]
你发这种issue有何意义？显示你是SB？

**Comment by lk9100** [comment]
这人是来搞笑的。。大家放松一下

**Comment by kevinkassimo** [comment]
@ry @qti3e Please close this issue ASAP.

I would suggest, if possible, at current stage, close any issue with Chinese title. Better through a bot. There were a few influential articles published on Chinese forums and other platforms that originally served to introduce the core concept of demo, but now I guess we have all seen the unintended insidious effects. People in China tend to treat Github less seriously, as if it is just another Reddit.

感觉作为国人脸都被你们丢光了...能不能老老实实呆在贴吧水？
