### ISSUE TITLE
一个字干

### ISSUE THREAD

**Issue by h5-zzh** [ry/deno#36]

**Comment by laosb** [comment]
请勿在 Issues 页面无意义灌水，此类行为属于对 Issues 区的滥用。

Please stop sending anything that is not related to this project. Doing this is a kind of abusing Issue Tracker.

**Comment by beary** [comment]
请勿在 Issues 页面无意义灌水，此类行为属于对 Issues 区的滥用。

Please stop sending anything that is not related to this project. Doing this is a kind of abusing Issue Tracker.
