### ISSUE TITLE
一入前端深似海。

### ISSUE THREAD

**Issue by ewjx** [ry/deno#37]

**Comment by laosb** [comment]
请勿在 Issues 页面无意义灌水，此类行为属于对 Issues 区的滥用。

Please stop sending anything that is not related to this project. Doing this is a kind of abusing Issue Tracker.

**Comment by relign** [comment]
请勿在 Issues 页面无意义灌水，此类行为属于对 Issues 区的滥用。

Please stop sending anything that is not related to this project. Doing this is a kind of abusing Issue Tracker.

**Comment by Nimor123** [comment]
请勿在 Issues 页面无意义灌水，此类行为属于对 Issues 区的滥用。

Please stop sending anything that is not related to this project. Doing this is a kind of abusing Issue Tracker.

**Comment by abnerCrack** [comment]
请勿在 Issues 页面无意义灌水，此类行为属于对 Issues 区的滥用。

Please stop sending anything that is not related to this project. Doing this is a kind of abusing Issue Tracker.

**Comment by Angelxiaotao** [comment]
请勿在 Issues 页面无意义灌水，此类行为属于对 Issues 区的滥用。

**Comment by CupNoodleFork** [comment]
请勿在 Issues 页面无意义灌水，此类行为属于对 Issues 区的滥用。

Please stop sending anything that is not related to this project. Doing this is a kind of abusing Issue Tracker.

**Comment by ichengde** [comment]
请勿在 Issues 页面无意义灌水，此类行为属于对 Issues 区的滥用。

Please stop sending anything that is not related to this project. Doing this is a kind of abusing Issue Tracker.

**Comment by shenzhenjinma** [comment]
请勿在 Issues 页面无意义灌水，此类行为属于对 Issues 区的滥用。

Please stop sending anything that is not related to this project. Doing this is a kind of abusing Issue Tracker.

**Comment by huweisir** [comment]
请勿在 Issues 页面无意义灌水，此类行为属于对 Issues 区的滥用。

Please stop sending anything that is not related to this project. Doing this is a kind of abusing Issue Tracker.

**Comment by Nimor123** [comment]
保持好队形 不要乱

**Comment by Angelxiaotao** [comment]
请勿在 Issues 页面无意义灌水，此类行为属于对 Issues 区的滥用。

Please stop sending anything that is not related to this project. Doing this is a kind of abusing Issue Tracker.

**Comment by geograous** [comment]
请勿在 Issues 页面无意义灌水，此类行为属于对 Issues 区的滥用。

Please stop sending anything that is not related to this project. Doing this is a kind of abusing Issue Tracker.

**Comment by dinglittle** [comment]
请勿在 Issues 页面无意义灌水，此类行为属于对 Issues 区的滥用。

Please stop sending anything that is not related to this project. Doing this is a kind of abusing Issue Track

**Comment by dwqs** [comment]
@ry This issue is no sense, close it, please.

**Comment by lizebang** [comment]
@ewjx 
Please close this issue.
请关掉这个 issue。
