### ISSUE TITLE
Use bindgen to manage FFI

### ISSUE THREAD

**Issue by robbym** [ry/deno#372]
Any thoughts on using https://github.com/rust-lang-nursery/rust-bindgen for generation of the FFI stuff?

**Comment by ry** [comment]
For interfacing with the core deno.h stuff - I prefer to manually maintain these interfaces right now. Reasons:

1. The C interfaces are meant to be minimal. By avoiding autogenerated bindings, we force ourselves to think carefully about what gets added.
1. We are still iterating quickly on large structures of the project. Generated code is extra complexity in an already very complex build process. I would like to avoid any unnecessary complexity.
1. Generated code makes projects less "greppable".

In the future we will discuss how to support extension modules - perhaps this will be a useful tool then. We can discuss in a month or two - for now there are more fundemental things to get working first.
