### ISSUE TITLE
请勿在 Issues 页面无意义灌水，此类行为属于对 Issues 区的滥用。

### ISSUE THREAD

**Issue by Angelxiaotao** [ry/deno#39]
请勿在 Issues 页面无意义灌水，此类行为属于对 Issues 区的滥用。

Please stop sending anything that is not related to this project. Doing this is a kind of abusing Issue Tracker.

**Comment by DanielQinSir** [comment]
这些灌水的人素质真是极差,好好一个技术社区被玩成了贴吧,丢人丢到全世界了

**Comment by LarryLawrence** [comment]
那位老哥的心情可以理解。论架构深度，前端的纵深远不及后端，于是各类框架轮子层出不穷，横向铺开。

**Comment by yanhaijing** [comment]
来晚了，想来看看热闹，都删了
