### ISSUE TITLE
I'm sorry to see where you can see the detailed instructions.

### ISSUE THREAD

**Issue by jielanglang** [ry/deno#40]
有详细的使用么说明么？ 留下地址 谢谢

**Comment by laosb** [comment]
请勿在 Issues 页面无意义灌水，此类行为属于对 Issues 区的滥用。

Please stop sending anything that is not related to this project. Doing this is a kind of abusing Issue Tracker.

**Comment by beary** [comment]
一会就刷了一堆中文的无聊 issue ，丢人现眼
