### ISSUE TITLE
Granular access permissions

### ISSUE THREAD

**Issue by bakerface** [ry/deno#410]
Really just thinking out loud here, especially since the feature I am about to talk about would be a language extension, but I would like to get your feedback on this idea. What if we could import files with access permissions rather than giving access to the whole application, as a way to limit access for 3rd party sources. So rather than `--alow-write` and `--allow-net`, something like the following:

```
// import without access to networking or filesystem
import { assign } from "https://some.questionable.website.com/object-assign.ts";

// import with access to networking
import { fetch } allowing { net } from "https://some.questionable.website.com/whatwg-fetch.ts";

// import with access to filesystem
import { watch } allowing { fs } from "https://some.questionable.website.com/watch-fs.ts";

// import with access to both networking and filesystem
import { watch } allowing { fs, net } from "https://some.questionable.website.com/watch-fs.ts";
```

The syntax is pretty much arbitrary, but I just wanted to get your feedback on the ability to have more granular control over permissions.

Thanks,
Chris

**Comment by ry** [comment]
Hi Chris, this isn't really possible - we can only control permissions on a VM level. See also #171.

**Comment by redradist** [comment]
> Hi Chris, this isn't really possible - we can only control permissions on a VM level. See also #171.

@ry Why it is not possible ? V8 do not provide script file which calls specific bond method ?
Maybe then it is better to patch V8 by adding this functionality ?

As for me as more scripts added, at the end users prefer to add `-A`, which completely eliminate security ...

With granular permissions, deno modules would be like Android and iOS apps that requires some permissions, granular permissions would solve issue with `-A`
