### ISSUE TITLE
upgrade to latest typescript

### ISSUE THREAD

**Issue by ry** [ry/deno#417]
1. edit version here: https://github.com/ry/deno/blob/6b49944da1e7b06aeba04b1c0ded8e3fdb3c436b/package.json#L21
2. run `./tools/sync_third_party.py`
3. commit changes in third_party repo. send a pull request to https://github.com/ry/deno_third_party (only add relevant files - there may be others that were mistakenly not committed yet)
4. fix any errors: `./tools/test.py out/debug`
5. run `tools/format.py`
6. send me a PR.

This is probably harder than just upgrading. Potentially difficult but good intro to `runtime.ts`.

**Comment by kitsonk** [comment]
From the experience with Deno 1, there is this issue: Microsoft/TypeScript#24638 which is only resolved in TypeScript 3.0 (which is in RC at the moment and should be released any moment).

**Comment by kitsonk** [comment]
Been looking at 3.0.0-rc in advance of its initial release.  There was a restructuring of the built in libs, and `lib.d.ts` now "drags in" scripthost, webworker and dom libs.  I tried to use `--noLib` which might actually be better for deno longer term, but the problem with that at is `runtime.ts` is only using single module compiling which means additional files (like `lib.esnext.d.ts`) can be specified.

**Comment by kitsonk** [comment]
Updated the WIP PR.  Found it was easier to introduce `lib.deno.d.ts` and have the language service that is created at runtime use it as the default library.  Now the runtime typings should better align to what is actually available and `lib.deno.d.ts` becomes the place where the global runtime environment for deno is described and applied to executed code.

**Comment by ry** [comment]
Fixed in 36fa1cea4a6c7c4ae5ac93974843fcdcd4557fef
