### ISSUE TITLE
tslint and out/debug/gen/msg_generated.ts

### ISSUE THREAD

**Issue by ry** [ry/deno#420]
When running `./tools/lint.py` locally I get many errors on `out/debug/gen/msg_generated.ts`. 

1. Why isn't this happening in Travis? We run lint. https://github.com/ry/deno/blob/6b49944da1e7b06aeba04b1c0ded8e3fdb3c436b/.travis.yml#L42
2. Fix the problem by ignoring msg_generated.ts.

cc @kitsonk

**Comment by kitsonk** [comment]
I will raise a PR to clean this up but:

1. Because the `tsconfig.json` which TSLint uses does not include the information to resolve the generated modules on Travis.  We are now injecting that via the `rollup.config.js`.  So `tslint` cannot "see" the module.
2. Will be fixed in the PR.
