### ISSUE TITLE
delete

### ISSUE THREAD

**Issue by dearzoe** [ry/deno#50]
im so sorry

**Comment by yanhaijing** [comment]
好像搜不到了

**Comment by tuxl** [comment]
兄弟 不要吧这里当贴吧好不

**Comment by lei-jinlei** [comment]
找不到这哥们了，记录被删了吧

**Comment by sgf** [comment]
pls dont open any issue like this OK? u know the auther is not knoe much chinese.
and this is not a really issue of this Project!
This will disturb the author!!!
pls Delete or Close this Issue!

**Comment by FloydaGithub** [comment]
@sgf This is a joke for children's day! :)

**Comment by sgf** [comment]
@FloydaGithub 
**dont let your joke waste other's time !!!**

**Comment by zyn86** [comment]
@sgf 英语不错

**Comment by beary** [comment]
@dearzoe 请关闭这个 issue

**Comment by gztchan** [comment]
@dearzoe There is no difference between you and the guy you mention with a screenshot. Please open meaningful issues that makes contribution. :)

**Comment by pod4g** [comment]
@FloydaGithub children你妈的day，你爱听笑话去别的地方发，脑残一样

**Comment by justjavac** [comment]
兄弟，你的行为和他有什么区别呢。已经到你的首页举报你了

**Comment by amorist** [comment]
please close

**Comment by xiaoshu896448** [comment]
shit doing

**Comment by kanting** [comment]
Why always pose unrelated thing on issue? @ry  please close this

**Comment by Rholais** [comment]
Is there any relation between you issue and this repository?

**Comment by zhihuitang** [comment]
iamzfj007这个用户都没有了, 连用户都删啊, 好怕怕

**Comment by FEhao** [comment]
unrelated issue, plz CLOSE it.
SHAME on anyone who takes it as a  joke.

**Comment by justjavac** [comment]
我提供一个模板，大家可以去 @dearzoe 首页点击举报：

> Someone submits an unfriendly issue to the ry/deno repository. Although the relevant issue has been deleted, the user @dearzoe continues to submit a similar issue. Everyone hopes that github can punish its behavior and delete the corresponding issue.
> 
> Https://github.com/ry/deno/issues/50
> 
> Thx.
