### ISSUE TITLE
Please close this project for now.

### ISSUE THREAD

**Issue by jackey** [ry/deno#53]
You created node few years ago and it's very exciting project. we using and enjoy it. but it has a very big problem , we call "callback hell" or "callback shit". of course, some people create few solutions. but you didn't do anything to solve the problem and leaved node project. 

Now, you back with deno, also it's basic on v8 engine.  Will i like it ? no, i don't like it as i don't like you. 

Before you created something that has relationship between javascript & v8 , please go to node project and fix the issues first.  [here you go](https://github.com/nodejs/node)

Before that, please close this project. Ok ? 

Thanks.

**Comment by qti3e** [comment]
@jackey Have you aware heard anything about [async/await](https://github.com/tc39/ecmascript-asyncawait) ???

**Comment by jackey** [comment]
@qti3e 
I tried many solution for async problem, none of them perfect.  But as creator , he has more responsibility to find better solution from core v8 , not just npm package. 

Do u know how many years of php author to maintained PHP ?  Python ?
Ry just like a child that boring a toy and then change new one.  

thanks.

**Comment by qti3e** [comment]
@jackey Everyone is free to do whatever he/she wants to do in his/her life : )

By leaving Node, he just made a personal decision, you can't ask why...

**Comment by jackey** [comment]
@qti3e 
As u said it's free to do whatever he wants. But we have a word "responsibility" . He doesn't have it .

**Comment by styfle** [comment]
@jackey Why do you no longer maintain [markdown](https://github.com/jackey/markdown)?

There are at least 10 people who starred it and you stopped working on it since [2015](https://github.com/jackey/markdown/commits/master)!

Do you have a responsibility to maintain it?

**Comment by jackey** [comment]
@styfle 
It's totally difference from node. None of them to use it.

**Comment by kiddkai** [comment]
@jackey please provide constructive feedbacks and make real contributions to the oss community. 
And please, read the guidelines https://opensource.guide
