### ISSUE TITLE
How about draw picture of the Deno's architecture?

### ISSUE THREAD

**Issue by JackieLs** [ry/deno#61]
May be we could know how to code,  but more eager to know the architecture. So could we have an article to introduce it more detailed？

**Comment by indexmotion** [comment]
Yes, a clear picture of the Deno's architecture can lead us newbies to explore the sources conveniently.

**Comment by hufeng** [comment]
Yes, Yes, Yes!

**Comment by qti3e** [comment]
![image](https://user-images.githubusercontent.com/13242052/40822567-1011df28-6582-11e8-8d77-a7fa422093eb.png)
@ry Do you confirm this?

**Comment by monkingxue** [comment]
@qti3e I like this graph and it's so clear, we can add it to README.

**Comment by qti3e** [comment]
@monkingxue Thanks for the suggestion : )
But it's my point of view and Ryan might want to present this project in some other ways...
let's wait till he says something...

**Comment by hufeng** [comment]
@qti3e [ts compiler] [Fetch ts]  Is it executed in V8?

**Comment by qti3e** [comment]
@hufeng we have this `Eval()` function defined in `main.go` to evaluate a **JS (not TS)** string inside our V8 contex:
https://github.com/ry/deno/blob/b723ab126f5cc37b27d914e6cbdba9a4f9ce1c71/main.go#L100-L105

We use this function (`Eval()`) in `Init()` to load our main ** JS ** file:
https://github.com/ry/deno/blob/b723ab126f5cc37b27d914e6cbdba9a4f9ce1c71/main.go#L94-L97

As you see this uses a function called `stringAsset()`, you can checkout `go-bindata` for more information... but for now we just need to know it loads a file, which is `main.js`

`main.js` is a pre-compiled ts file in `dist` dir, look at this Makefile entity:
https://github.com/ry/deno/blob/b723ab126f5cc37b27d914e6cbdba9a4f9ce1c71/Makefile#L55-L57

Finally, we executed Deno's core js file inside V8 and that's the beginning of all magics : )

FYI; You can find codes related to ts compiled inside `runtime.ts`

**Comment by hufeng** [comment]
@qti3e thank you. ❤️

**Comment by ry** [comment]
http://tinyclouds.org/jsconf2018.pdf
