### ISSUE TITLE
How to build deno in Windows and cygwin env?

### ISSUE THREAD

**Issue by kimmking** [ry/deno#81]
Hi, guys,
    How to build deno in Windows and cygwin env?
    Any suggestions, thx.

**Comment by FrankFang** [comment]
I believe it's impossible to build deno in cygwin.
But you can try docker for Windows 
https://github.com/ry/deno/pull/63

**Comment by ry** [comment]
It's not possible with the current build scripts, but I want to support windows well and natively eventually.
