### ISSUE TITLE
discussion: struct the browser-compatible APIs

### ISSUE THREAD

**Issue by yorkie** [ry/deno#82]
@ry @qti3e I just have a proposal about which Web APIs should be supported:

- High level
  - [x] Console
  - [x] URL
  - [ ] File/FileList/FileReader/Blob
  - [ ] XMLHttpRequest/Fetch
  - [ ] WebSocket
  - [ ] URLSearchParams
- Middle level
  - [ ] AudioContext/AudioBuffer
  - [ ] Canvas

Btw, supports WebGL that makes like `tfjs` could run at deno, and make use of the GPUs, it might be interesting personally :)

**Comment by qti3e** [comment]
Thanks, Yazhong! I like supporting WebGl btw, it's a cool idea! (ML in Deno!) : )

**Comment by monkingxue** [comment]
Maybe we should support XMLHttpRequest or WebSocket first because they are basement.

**Comment by qti3e** [comment]
It's a good topic and discussion, but we should remember that Deno is an early stage software and above everything, we should make it work in a good way and build  all the foundations of the project much stronger then we can start working on new features : )

**Comment by ztplz** [comment]
@ry  @qti3e  I think we should write a todo-list of api that we need to implement next.
I am glad to make PR for this great project.

**Comment by benjamingr** [comment]
What about `URL` and `URLSearchParams`?

**Comment by qti3e** [comment]
@benjamingr yeah right,but we already have `URL`, see [url.js](https://github.com/ry/deno/blob/master/url.js)

@yorkie I've updated your TODO list, I hope you don't mind : )

**Comment by yorkie** [comment]
Never mind, feel free to update the list :)

**Comment by ry** [comment]
Yes I want to have browser APIs like this. Submit PRs otherwise please keep the issues quiet for technical matters.
