### ISSUE TITLE
APIs proposal

### ISSUE THREAD

**Issue by sbFrankFang** [ry/deno#84]
@ry @qti3e I just have a proposal about which Web APIs should be supported:
High level
  Console
  File/FileList/FileReader/Blob
  XMLHttpRequest
  WebSocket
Middle level
  AudioContext/AudioBuffer
  Canvas
Btw, supports WebGL that makes like tfjs could run at deno, and make use of the GPUs, it might be interesting personally :)

and your code is very six, i must give you double click,six six six.

Wait until I have the many money to send you a plane and a yacht.

We work together, come on!

**Comment by 44886** [comment]
very good

**Comment by lopo1983** [comment]
tree new bee 👍

**Comment by qti3e** [comment]
duplicate of #82

**Comment by FrankFang** [comment]
It's not me
