### ISSUE TITLE
Maybe we should organize the file structure

### ISSUE THREAD

**Issue by monkingxue** [ry/deno#86]
I found that the most of files were placed randomly. Maybe we can organize them and write some introductions to help other contributors to get hold of the code.

**Comment by qti3e** [comment]
@monkingxue You're right! but adding more dirs will cause more complexity, and I think it's a bit soon to do it... : )

**Comment by monkingxue** [comment]
@qti3e Do we have some files like `roadmap` or `we should do`? I hope to contribute to this project  very much but I don't know what I should prioritize.

**Comment by whtiehack** [comment]
just a todo list   
https://github.com/ry/deno/blob/master/TODO.txt

**Comment by monkingxue** [comment]
@whtiehack I have read this file but I think it's informal.

**Comment by monkingxue** [comment]
@qti3e Thank u so much~

**Comment by ry** [comment]
No file reorg needed at this time.
