### ISSUE TITLE
哎呦，不错，这个叼

### ISSUE THREAD

**Issue by YangyagQ** [ry/deno#89]
dear ry,
nice work,your code is very six.

old iron , double click six six six .
thanks this old iron's plane.

**Comment by FrankFang** [comment]
spam

**Comment by YangyagQ** [comment]
@FrankFang  i know you，I just saw you , You are not moral, I don't want to discuss technology with you
,shame on you.

**Comment by Adherentman** [comment]
please close this issue

**Comment by ChouXiangTVswindleChen** [comment]
那真的牛皮

**Comment by YangyagQ** [comment]
@Adherentma  ，Please do not，I want to speak in a better way for DeNO tomorrow. Thank you.

**Comment by monkingxue** [comment]
@qti3e Please close this issue and I am soooo sorry for the behavior of a small part of Chinese developers.

**Comment by Hobr** [comment]
**丢人**

**Comment by YangyagQ** [comment]
@qti3e 
我觉得人人都有应该有为DENO说话的权利，为了DENO更美好的明天。我们为了同一个目标，工作在一起，应该合理的，自由的讨论的，不是吗？

**Comment by YangyagQ** [comment]
@qti3e ,
I think everyone should have the right to speak for DENO, for a better tomorrow for DENO. We work together for the same goal, we should discuss it freely and rationally, can't we?

**Comment by pexcn** [comment]
Spam, reported.

**Comment by joname1** [comment]
Facking spam, get the fack outta here!

**Comment by YangyagQ** [comment]
@joname1 
oh,no,Why are you so rude?

**Comment by YangyagQ** [comment]
DeNO will have a great tomorrow. It's not just the author's, it's also the wealth of developers all over the world.

**Comment by ZhangZisu** [comment]
GitHub issue is not a place for you to argue around. Spam, reported.

**Comment by YangyagQ** [comment]
@ZhangZisu  em。。。 This is not an argument, it is a harmonious discussion.

**Comment by qwertyuiop6** [comment]
当直播间呢，秀下限？

**Comment by ZhangZisu** [comment]
*Harmonious* discussion? Em, Please change the title into English and show the respect of the developer first. Otherwise please close the issue NOW.

**Comment by YangyagQ** [comment]
it is a harmonious discussion. You scared me. 
Every country's developers should talk about a better Deno together. Everyone in the country can make a better tomorrow for Deno. Are you discriminating against the language of the my motherland
?
