### ISSUE TITLE
discussion: distributed deno backends and configurability

### ISSUE THREAD

**Issue by yorkie** [ry/deno#91]
Hi, Denors,

Currently the Deno is using `msg.pb` to define all messages between the JS and Golang backend. How about making the arch of the TS & Golang to be more flexible by introducing the IPC/RPC messaging?

For instance, when somebody does a http request in TS, this message should be dispatched to one of configured backends. BTW we are able to do write the backend by other languages like erlang, rustlang or C/C++. This would make Deno would be birth for distributed system.

This is also one of the features that I hope to bring to Deno :)

/cc @ry @qti3e

**Comment by ry** [comment]
I'm not sure I understand... That is the purpose of msg.proto.

**Comment by yorkie** [comment]
Deno currently just does pass these messages between in 1 process, what I mean is it could be in different processes and even machines, and yes, that might be the purpose of msg.proto :)

**Comment by ry** [comment]
Potentially some day. Not any time soon.
