### ISSUE TITLE
go get v8worker2 Direct fetching of that commit failed?

### ISSUE THREAD

**Issue by Adherentman** [ry/deno#92]
my OS Mac10.13.4
I viewed #60 issue，And Performed each of the above, but still does not work.

- I listen to @ry  at http://osxdaily.com/2014/02/12/install-command-line-tools-mac-os-x/ to install `xcode-select`
<img width="759" alt="wx20180601-235904 2x" src="https://user-images.githubusercontent.com/26477346/40850648-caa92d94-65f7-11e8-980b-073aaf1b170f.png">

- And `pkg-config 0.29.2 is already installed`

- I try `go get -u github.com/ry/v8worker2` agin.
<img width="1014" alt="wx20180601-233535 2x" src="https://user-images.githubusercontent.com/26477346/40850346-f418cbd6-65f6-11e8-905b-99bbf49f8d2b.png">

- then git `git submodule update --init`
<img width="978" alt="wx20180601-233658 2x" src="https://user-images.githubusercontent.com/26477346/40850428-28dcbac6-65f7-11e8-9434-175a52d46efb.png">

I don't know what happened。

**Comment by qti3e** [comment]
@Adherentman It seems your cloned version of v8 is corrupted, I'm not a git expert but maybe re-cloning `v8` might work...
```bash
cd $GOPATH/src/github.com/ry/v8worker2
rm -rf v8
git clone https://github.com/v8/v8.git
git checkout fe12316ec4b4a101923e395791ca55442e62f4cc
```

**Comment by wbgbg** [comment]
I use depot tools to fetch v8.

```
export PATH=$PATH:$GOPATH/src/github.com/ry/v8worker2/depot_tools
cd $GOPATH/src/github.com/ry/v8worker2
rm -rf v8
fetch v8
cd v8
git checkout fe12316
```

**Comment by ztplz** [comment]
Try vpn please. 
I build success in my mac.

**Comment by maxmcd** [comment]
FWIW I'm also getting this error on a fresh build within a docker image. Can reproduce with:
```dockerfile
FROM golang:1.10-stretch
RUN go get -u github.com/ry/v8worker2
```
A manual clone of v8 still works as a fix.

**Comment by Foveluy** [comment]
@Adherentman  most Chinese users have to use VPN .
Not only applying to browser but also your terminal, and make sure to set up a proxy for git:
```bash
git config --global http.proxy "localhost:xxxx"
git config --global https.proxy "localhost:xxxx"
```

**Comment by Adherentman** [comment]
@Foveluy @ztplz Thanks,I promise my vpn is working。
Now，I'm try clone v8 👍

**Comment by Adherentman** [comment]
@qti3e @ztplz  
First of all thank everyone for your help. The previous issue has been solved.

But I get have new Issue, OS: Macos 10.13.4
- In #71 , I try `export PATH="$PATH:$GOPATH/bin"`.But not work
<img width="467" alt="wx20180602-121239 2x" src="https://user-images.githubusercontent.com/26477346/40870258-58250240-665e-11e8-88f1-e1637ea52fd1.png">

**Comment by Foveluy** [comment]
@Adherentman 

Great, it seems like you have made it to the last step, just try append the following to your `~/.zshrc`
```bash
export GOROOT=/usr/local/go # where your `go` sitting, usually here ( Mac )
export GOPATH=$HOME/go # means `~/go` 
export PATH=$PATH:$HOME/go/bin:$GOPATH/bin
```

after doing so, try to get `protoc-gen-go` again.

**Comment by ztplz** [comment]
@Adherentman   Reinstall  protoc-gen-go and  export PATH="$PATH:$GOPATH/bin".

**Comment by Adherentman** [comment]
@Foveluy @ztplz nice,Thanks everyone again
it's work:)
I will close this issue! And hope this issue will help people who have the same problem!
<img width="785" alt="wx20180602-142452 2x" src="https://user-images.githubusercontent.com/26477346/40871591-edefe60c-6670-11e8-83c5-0e1fd559ce03.png">
