### ISSUE TITLE
Too Much Noise

### ISSUE THREAD

**Issue by ry** [ry/deno#94]
I appreciate and am excited about all the interest in this project. However, please understand that this is very much a non-functional prototype. There's a huge amount of heavy lifting to do still. Unless you are participating in that, **please maintain radio silence**.

**Comment by alanchenchen** [comment]
Can't agree more

**Comment by amorist** [comment]
translation
实在太吵了
感谢所有对这个项目有兴趣的人，对此，我很高兴。 但是，请理解，目前这还只是一个原型。 还有很多的事情要做解决。 除非你参与贡献，否则请保持沉默。（Amor的个人观点：除非你参与，否则，你无权干涉别人。每个人都有自己要做，想做的事情。指责别人的时候，想想你干了什么，你只是伸伸手，动动嘴，敲敲键盘，拿别人的劳动成果赚钱，要求太多了，不喜欢，可以不用，不喜欢这门语言，可以换其它的语言，干不了编程，可以去卖臭豆腐、煎饼果子，这些，也很高深）

**Comment by 44886** [comment]
@amorist 这段文字思虑了很久吧，修改了3次。

你的观点非常值得赞同，可就是不知道你是如何总结而来的，没有看出哪儿有人说不喜欢、更没有人责怪社区和作者。

大家都在为新项目的诞生而庆祝和欢呼，到是你在这里莫名其妙就自我高潮了。

**Comment by 44886** [comment]
@ry 
每个人都在为你的新项目而鼓掌，感谢你给大家带来的新希望。
但github里 ，除了issue没有其他地方可以交流，所以，请体谅大家的热忱。

**Comment by 44886** [comment]
@amorist  我觉得这项目会火，难道不会？
