### ISSUE TITLE
Where is the Asset Function definition?

### ISSUE THREAD

**Issue by terasum** [ry/deno#97]
I can't find the `Asset` function definition, but it compiles and works well, I'm confused. where can I get the definition of `Asset` in the `stringAsset` function?

```
func stringAsset(path string) string {
	data, err := Asset("dist/" + path)
	check(err)
	return string(data)
}
```

Does this function generated by `go-bindata`? I can't find it in the `asset.go`.

Please forgive me for my stupid question.

Thanks.

**Comment by ry** [comment]
Yes it comes from go-bindata. It's a generated function in a file called asset.go - which contains the parcel bundled javascript - so it can be included in the executable.
